INSERT INTO input_items (category_id, code, is_system_defined, sort_order, is_active, item_metadata)
SELECT id, 'POTASSIUM_NITRATE', true, 1, true, '{"trade_name": "Potassium Nitrate", "brand": "Multi-brands", "category": "macronutrient (K,N)", "nutrients": ["Nitrogen 13% (NO3)", "Potassium (K2O) 46%"], "npk_ratio": "13-0-46", "form": "water soluble crystalline / granules", "solubility": "high (water soluble)", "manufacturer": "Multi-brands (e.g., Haifa, IFFCO, Mahadhan)", "storage_instructions": "Store in dry, cool place; keep away from moisture", "additional": {"common_uses": "foliar spray, fertigation"}}'::jsonb FROM input_item_categories WHERE code = 'FERTILIZER' UNION ALL 
SELECT id, 'CALCIUM_NITRATE', true, 1, true, '{"trade_name": "Calcium Nitrate", "brand": "Multi-brands", "category": "secondary nutrient (Ca, N)", "nutrients": ["Nitrogen 15.5% (NO3)", "Calcium 18.5% (Ca)"], "npk_ratio": "15.5-0-0; Ca 18.5%", "form": "granular / soluble", "solubility": "high (water soluble)", "manufacturer": "Multi-brands (e.g., ICL, Utkarsh, Positive Plus)", "storage_instructions": "Keep dry; do not mix with phosphate-containing fertilizers", "additional": {"common_uses": "correct calcium deficiency, foliar and fertigation"}}'::jsonb FROM input_item_categories WHERE code = 'FERTILIZER' UNION ALL 
SELECT id, 'MAGNESIUM_NITRATE', true, 1, true, '{"trade_name": "Magnesium Nitrate", "brand": "Multi-brands", "category": "secondary nutrient (Mg, N)", "nutrients": ["Nitrogen 11% (NO3)", "Magnesium ~9.6% (Mg)"], "npk_ratio": "11-0-0; Mg ~9.6%", "form": "water soluble crystalline", "solubility": "high", "manufacturer": "Multi-brands (e.g., Haifa, Shiv Chemicals, Utkarsh)", "storage_instructions": "Store dry; avoid mixing with phosphates", "additional": {"note": "Often sold as hexahydrate or other hydrates"}}'::jsonb FROM input_item_categories WHERE code = 'FERTILIZER' UNION ALL 
SELECT id, 'FERROUS_SULPHATE', true, 1, true, '{"trade_name": "Ferrous Sulphate", "brand": "Multi-brands", "category": "micronutrient (Fe)", "nutrients": ["Iron (Fe) ~20% (as FeSO4Â·7H2O)"], "npk_ratio": "Fe ~20%", "form": "crystalline powder / granules", "solubility": "water soluble", "manufacturer": "Multi-brands (industrial/Ag suppliers)", "storage_instructions": "Store in cool dry place; protect from moisture", "additional": {"common_uses": "soil amendment, foliar Fe source; treat iron chlorosis"}}'::jsonb FROM input_item_categories WHERE code = 'FERTILIZER' UNION ALL 
SELECT id, 'ZINC_SULPHATE', true, 1, true, '{"trade_name": "Zinc Sulphate", "brand": "Multi-brands", "category": "micronutrient (Zn)", "nutrients": ["Zinc (Zn) ~21% (as ZnSO4Â·7H2O)"], "npk_ratio": "Zn ~21%", "form": "crystalline powder / granular", "solubility": "water soluble", "manufacturer": "Multi-brands", "storage_instructions": "Keep dry; store in sealed packaging", "additional": {"common_uses": "soil and foliar application to correct Zn deficiency"}}'::jsonb FROM input_item_categories WHERE code = 'FERTILIZER' UNION ALL 
SELECT id, 'MAGNESIUM_SULPHATE', true, 1, true, '{"trade_name": "Magnesium Sulphate", "brand": "Multi-brands", "category": "secondary nutrient (Mg,S)", "nutrients": ["Magnesium (Mg) ~9.8% (as MgSO4Â·7H2O)", "Sulfur (S) ~12% (approx)"], "npk_ratio": "Mg ~9.8%; S ~12%", "form": "crystalline / powder", "solubility": "high (water soluble)", "manufacturer": "Multi-brands", "storage_instructions": "Store dry; hygroscopic", "additional": {"common_uses": "foliar and soil application; correct Mg deficiency"}}'::jsonb FROM input_item_categories WHERE code = 'FERTILIZER' UNION ALL 
SELECT id, 'SULPHATE_OF_POTASH_(SOP)', true, 1, true, '{"trade_name": "Sulphate of Potash (SOP)", "brand": "Multi-brands", "category": "macronutrient (K)", "nutrients": ["Potassium (K2O) ~50%"], "npk_ratio": "0-0-50", "form": "crystalline / granule", "solubility": "moderate to high (water soluble)", "manufacturer": "Multi-brands (e.g., Haifa, IFFCO)", "storage_instructions": "Keep dry; avoid mixing with chloride-sensitive crops", "additional": {"common_uses": "foliar, fertigation, basal potash source for chloride-sensitive crops"}}'::jsonb FROM input_item_categories WHERE code = 'FERTILIZER' UNION ALL 
SELECT id, 'MONO_AMMONIUM_PHOSPHATE_(MAP)', true, 1, true, '{"trade_name": "Mono Ammonium Phosphate (MAP)", "brand": "Multi-brands", "category": "macronutrient (N,P)", "nutrients": ["Nitrogen 12% (N)", "P2O5 61% (P)"], "npk_ratio": "12-61-0", "form": "crystalline / water soluble", "solubility": "high", "manufacturer": "Multi-brands (e.g., IFFCO, Mahadhan)", "storage_instructions": "Store dry; hygroscopic; avoid mixing with alkaline substances", "additional": {"common_uses": "starter fertilizer, foliar and fertigation (specialty soluble grades)"}}'::jsonb FROM input_item_categories WHERE code = 'FERTILIZER' UNION ALL 
SELECT id, 'MONO_POTASSIUM_PHOSPHATE_(MKP)', true, 1, true, '{"trade_name": "Mono Potassium Phosphate (MKP)", "brand": "Multi-brands", "category": "macronutrient (P,K)", "nutrients": ["P2O5 52%", "K2O 34%"], "npk_ratio": "0-52-34", "form": "water soluble crystalline", "solubility": "high", "manufacturer": "Multi-brands (e.g., IFFCO, Haifa)", "storage_instructions": "Store dry in sealed packaging", "additional": {"common_uses": "foliar, fertigation; pH neutral source of P and K"}}'::jsonb FROM input_item_categories WHERE code = 'FERTILIZER' UNION ALL 
SELECT id, 'BORON_(BORIC_ACID_/_BORAX)', true, 1, true, '{"trade_name": "Boron (Boric acid / Borax)", "brand": "Multi-brands", "category": "micronutrient (B)", "nutrients": ["Boron (B) 17.5% (as boric acid) or ~11% (as borax)"], "npk_ratio": "B 17.5% (boric acid) / B ~11% (borax)", "form": "powder / crystalline", "solubility": "moderate (varies by salt)", "manufacturer": "Multi-brands", "storage_instructions": "Keep dry; avoid over-application (narrow range)", "additional": {"note": "Specify whether product is boric acid or borax when listing"}}'::jsonb FROM input_item_categories WHERE code = 'FERTILIZER' UNION ALL 
SELECT id, 'COPPER_SULPHATE', true, 1, true, '{"trade_name": "Copper Sulphate", "brand": "Multi-brands", "category": "micronutrient (Cu)", "nutrients": ["Copper (Cu) ~25% (as CuSO4Â·5H2O)"], "npk_ratio": "Cu ~25%", "form": "crystalline powder", "solubility": "water soluble", "manufacturer": "Multi-brands", "storage_instructions": "Store dry; corrosive to metals; keep sealed", "additional": {"common_uses": "correct copper deficiency; fungicidal properties in some mixes"}}'::jsonb FROM input_item_categories WHERE code = 'FERTILIZER' UNION ALL 
SELECT id, 'MANGANESE_SULPHATE', true, 1, true, '{"trade_name": "Manganese Sulphate", "brand": "Multi-brands", "category": "micronutrient (Mn)", "nutrients": ["Manganese (Mn) ~30% (typical anhydrous equiv; hydrate levels vary)"], "npk_ratio": "Mn ~30%", "form": "powder / crystalline", "solubility": "water soluble", "manufacturer": "Multi-brands", "storage_instructions": "Store dry; sensitive to air/moisture", "additional": {"common_uses": "correct manganese deficiency; foliar and soil application"}}'::jsonb FROM input_item_categories WHERE code = 'FERTILIZER' UNION ALL 
SELECT id, 'FE_EDTA_12%', true, 1, true, '{"trade_name": "Fe EDTA 12%", "brand": "Multi-brands", "category": "chelates (Fe)", "nutrients": ["Iron (Fe) 12% (as Fe-EDTA chelate)"], "npk_ratio": "Fe 12%", "form": "water soluble chelated powder", "solubility": "high (water soluble)", "manufacturer": "Multi-brands (e.g., Katyayani, Instacheal)", "storage_instructions": "Store in cool dry place; protect from sunlight and moisture", "additional": {"application": "foliar spray and fertigation; effective for correcting iron chlorosis"}}'::jsonb FROM input_item_categories WHERE code = 'FERTILIZER' UNION ALL 
SELECT id, 'ZN_EDTA_12%', true, 1, true, '{"trade_name": "Zn EDTA 12%", "brand": "Multi-brands", "category": "chelates (Zn)", "nutrients": ["Zinc (Zn) 12% (as Zn-EDTA chelate)"], "npk_ratio": "Zn 12%", "form": "water soluble chelated powder", "solubility": "high", "manufacturer": "Multi-brands (e.g., ZinGap, Sahib)", "storage_instructions": "Store dry; avoid alkaline mixing", "additional": {"application": "foliar spray and fertigation"}}'::jsonb FROM input_item_categories WHERE code = 'FERTILIZER' UNION ALL 
SELECT id, 'CA_EDTA_(CHELATED_CALCIUM)', true, 1, true, '{"trade_name": "Ca EDTA (Chelated Calcium)", "brand": "Multi-brands", "category": "chelates (Ca)", "nutrients": ["Calcium (Ca) ~10% (typical Ca-EDTA)"], "npk_ratio": "Ca ~10%", "form": "water soluble chelated powder/liquid", "solubility": "high", "manufacturer": "Multi-brands", "storage_instructions": "Store cool dry; label dependent", "additional": {"note": "Chelated calcium useful for foliar correction where Ca uptake is limited"}}'::jsonb FROM input_item_categories WHERE code = 'FERTILIZER' UNION ALL 
SELECT id, 'AMMONIUM_SULPHATE', true, 1, true, '{"trade_name": "Ammonium Sulphate", "brand": "Multi-brands", "category": "macronutrient (N,S)", "nutrients": ["Nitrogen 21% (as NH4)", "Sulfur ~24% (as SO4)"], "npk_ratio": "21-0-0; S ~24%", "form": "granular / crystalline", "solubility": "water soluble", "manufacturer": "Multi-brands (e.g., Coromandel, Nagarjuna)", "storage_instructions": "Store dry; hygroscopic; keep away from alkalies", "additional": {"common_uses": "acidifying nitrogen source; soil and fertigation use"}}'::jsonb FROM input_item_categories WHERE code = 'FERTILIZER'
ON CONFLICT (code, is_system_defined) WHERE is_system_defined = TRUE DO NOTHING;

INSERT INTO input_item_translations (input_item_id, language_code, name) VALUES 
((SELECT id from input_items where code='POTASSIUM_NITRATE') , 'en', 'Potassium Nitrate'), 
((SELECT id from input_items where code='CALCIUM_NITRATE') , 'en', 'Calcium Nitrate'), 
((SELECT id from input_items where code='MAGNESIUM_NITRATE') , 'en', 'Magnesium Nitrate'), 
((SELECT id from input_items where code='FERROUS_SULPHATE') , 'en', 'Ferrous Sulphate'), 
((SELECT id from input_items where code='ZINC_SULPHATE') , 'en', 'Zinc Sulphate'), 
((SELECT id from input_items where code='MAGNESIUM_SULPHATE') , 'en', 'Magnesium Sulphate'), 
((SELECT id from input_items where code='SULPHATE_OF_POTASH_(SOP)') , 'en', 'Sulphate of Potash (SOP)'), 
((SELECT id from input_items where code='MONO_AMMONIUM_PHOSPHATE_(MAP)') , 'en', 'Mono Ammonium Phosphate (MAP)'), 
((SELECT id from input_items where code='MONO_POTASSIUM_PHOSPHATE_(MKP)') , 'en', 'Mono Potassium Phosphate (MKP)'), 
((SELECT id from input_items where code='BORON_(BORIC_ACID_/_BORAX)') , 'en', 'Boron (Boric acid / Borax)'), 
((SELECT id from input_items where code='COPPER_SULPHATE') , 'en', 'Copper Sulphate'), 
((SELECT id from input_items where code='MANGANESE_SULPHATE') , 'en', 'Manganese Sulphate'), 
((SELECT id from input_items where code='FE_EDTA_12%') , 'en', 'Fe EDTA 12%'), 
((SELECT id from input_items where code='ZN_EDTA_12%') , 'en', 'Zn EDTA 12%'), 
((SELECT id from input_items where code='CA_EDTA_(CHELATED_CALCIUM)') , 'en', 'Ca EDTA (Chelated Calcium)'), 
((SELECT id from input_items where code='AMMONIUM_SULPHATE') , 'en', 'Ammonium Sulphate'), 
((SELECT id from input_items where code='POTASSIUM_NITRATE') , 'ta', 'பொட்டாசியம் நைட்ரேட்'), 
((SELECT id from input_items where code='CALCIUM_NITRATE') , 'ta', 'கால்சியம் நைட்ரேட்'), 
((SELECT id from input_items where code='MAGNESIUM_NITRATE') , 'ta', 'மெக்னீசியம் நைட்ரேட்'), 
((SELECT id from input_items where code='FERROUS_SULPHATE') , 'ta', 'இரும்பு சல்பேட்'), 
((SELECT id from input_items where code='ZINC_SULPHATE') , 'ta', 'துத்தநாக சல்பேட்'), 
((SELECT id from input_items where code='MAGNESIUM_SULPHATE') , 'ta', 'மெக்னீசியம் சல்பேட்'), 
((SELECT id from input_items where code='SULPHATE_OF_POTASH_(SOP)') , 'ta', 'பொட்டாஷ் சல்பேட் (SOP)'), 
((SELECT id from input_items where code='MONO_AMMONIUM_PHOSPHATE_(MAP)') , 'ta', 'மோனோ அம்மோனியம் பாஸ்பேட் (MAP)'), 
((SELECT id from input_items where code='MONO_POTASSIUM_PHOSPHATE_(MKP)') , 'ta', 'மோனோ பொட்டாசியம் பாஸ்பேட் (MKP)'), 
((SELECT id from input_items where code='BORON_(BORIC_ACID_/_BORAX)') , 'ta', 'போரான் (போரிக் அமிலம் / போராக்ஸ்)'), 
((SELECT id from input_items where code='COPPER_SULPHATE') , 'ta', 'காப்பர் சல்பேட்'), 
((SELECT id from input_items where code='MANGANESE_SULPHATE') , 'ta', 'மாங்கனீசு சல்பேட்'), 
((SELECT id from input_items where code='FE_EDTA_12%') , 'ta', 'Fe EDTA 12%'), 
((SELECT id from input_items where code='ZN_EDTA_12%') , 'ta', 'Zn EDTA 12%'), 
((SELECT id from input_items where code='CA_EDTA_(CHELATED_CALCIUM)') , 'ta', 'Ca EDTA (சேலேட்டட் கால்சியம்)'), 
((SELECT id from input_items where code='AMMONIUM_SULPHATE') , 'ta', 'அம்மோனியம் சல்பேட்'), 
((SELECT id from input_items where code='POTASSIUM_NITRATE') , 'ml', 'പൊട്ടാസ്യം നൈട്രേറ്റ്'), 
((SELECT id from input_items where code='CALCIUM_NITRATE') , 'ml', 'കാൽസ്യം നൈട്രേറ്റ്'), 
((SELECT id from input_items where code='MAGNESIUM_NITRATE') , 'ml', 'മഗ്നീഷ്യം നൈട്രേറ്റ്'), 
((SELECT id from input_items where code='FERROUS_SULPHATE') , 'ml', 'ഫെറസ് സൾഫേറ്റ്'), 
((SELECT id from input_items where code='ZINC_SULPHATE') , 'ml', 'സിങ്ക് സൾഫേറ്റ്'), 
((SELECT id from input_items where code='MAGNESIUM_SULPHATE') , 'ml', 'മഗ്നീഷ്യം സൾഫേറ്റ്'), 
((SELECT id from input_items where code='SULPHATE_OF_POTASH_(SOP)') , 'ml', 'സൾഫേറ്റ് ഓഫ് പൊട്ടാഷ് (SOP)'), 
((SELECT id from input_items where code='MONO_AMMONIUM_PHOSPHATE_(MAP)') , 'ml', 'മോണോ അമോണിയം ഫോസ്ഫേറ്റ് (MAP)'), 
((SELECT id from input_items where code='MONO_POTASSIUM_PHOSPHATE_(MKP)') , 'ml', 'മോണോ പൊട്ടാസ്യം ഫോസ്ഫേറ്റ് (MKP)'), 
((SELECT id from input_items where code='BORON_(BORIC_ACID_/_BORAX)') , 'ml', 'ബോറോൺ (ബോറിക് ആസിഡ് / ബോറാക്സ്)'), 
((SELECT id from input_items where code='COPPER_SULPHATE') , 'ml', 'കോപ്പർ സൾഫേറ്റ്'), 
((SELECT id from input_items where code='MANGANESE_SULPHATE') , 'ml', 'മാംഗനീസ് സൾഫേറ്റ്'), 
((SELECT id from input_items where code='FE_EDTA_12%') , 'ml', 'Fe EDTA 12%'), 
((SELECT id from input_items where code='ZN_EDTA_12%') , 'ml', 'Zn EDTA 12%'), 
((SELECT id from input_items where code='CA_EDTA_(CHELATED_CALCIUM)') , 'ml', 'Ca EDTA (ചീലേറ്റഡ് കാൽസ്യം)'), 
((SELECT id from input_items where code='AMMONIUM_SULPHATE') , 'ml', 'അമോണിയം സൾഫേറ്റ്')
ON CONFLICT (input_item_id, language_code) DO NOTHING;


INSERT INTO input_items (category_id, code, is_system_defined, sort_order, is_active, item_metadata)
SELECT id, 'ACTARA', true, 1, true, '{"trade_name": "Actara", "brand": "Syngenta", "category": "insecticide (systemic)", "active_ingredients": ["Thiamethoxam 25% WG"], "mode_of_action": ["systemic", "translaminar", "ingestion/contact"], "effective_against": ["aphids", "whiteflies", "thrips", "jassids", "leafhoppers"], "application_method": ["foliar spray", "seed treatment (label dependent)"], "form": "WG (Water Dispersible Granule)", "solubility": "water dispersible", "manufacturer": "Syngenta India Ltd.", "storage_instructions": "Store in original container in a cool, dry place away from direct sunlight and food/feed.", "additional": {}}'::jsonb FROM input_item_categories WHERE code = 'PESTICIDE' UNION ALL 
SELECT id, 'ADMIRE', true, 1, true, '{"trade_name": "Admire", "brand": "Bayer", "category": "insecticide (systemic, neonicotinoid)", "active_ingredients": ["Imidacloprid 70% WG"], "mode_of_action": ["systemic", "ingestion/contact"], "effective_against": ["sap sucking pests: aphids, jassids, whiteflies, thrips"], "application_method": ["soil drench", "foliar spray", "seed treatment (SKU dependent)"], "form": "WG (Water Dispersible Granule)", "solubility": "water dispersible", "manufacturer": "Bayer CropScience Ltd.", "storage_instructions": "Keep in original container in cool, dry place; avoid direct sunlight.", "additional": {}}'::jsonb FROM input_item_categories WHERE code = 'PESTICIDE' UNION ALL 
SELECT id, 'CONFIDOR', true, 1, true, '{"trade_name": "Confidor", "brand": "Bayer", "category": "insecticide (systemic, neonicotinoid)", "active_ingredients": ["Imidacloprid 17.8% SL"], "mode_of_action": ["systemic", "ingestion/contact"], "effective_against": ["aphids, whitefly, thrips, other sucking pests"], "application_method": ["foliar spray", "soil application", "seed treatment (label dependent)"], "form": "SL (Soluble Liquid)", "solubility": "soluble liquid", "manufacturer": "Bayer CropScience Ltd.", "storage_instructions": "Store in a cool, dry, locked place away from food and feed.", "additional": {}}'::jsonb FROM input_item_categories WHERE code = 'PESTICIDE' UNION ALL 
SELECT id, 'CORAGEN', true, 1, true, '{"trade_name": "Coragen", "brand": "FMC", "category": "insecticide (anthranilic diamide)", "active_ingredients": ["Chlorantraniliprole 18.5% SC"], "mode_of_action": ["ingestion/systemic; ryanodine receptor activator (IRAC Group 28)"], "effective_against": ["lepidopteran pests (caterpillars, borers, loopers)"], "application_method": ["foliar spray"], "form": "SC (Suspension Concentrate)", "solubility": "suspension", "manufacturer": "FMC India Pvt. Ltd.", "storage_instructions": "Store in original container, tightly closed, in a cool dry place.", "additional": {"mode_of_action_group": "IRAC Group 28"}}'::jsonb FROM input_item_categories WHERE code = 'PESTICIDE' UNION ALL 
SELECT id, 'JUMP', true, 1, true, '{"trade_name": "Jump", "brand": "Bayer", "category": "insecticide (phenylpyrazole)", "active_ingredients": ["Fipronil 80% WG"], "mode_of_action": ["contact, stomach action; GABA-gated chloride channel blocker"], "effective_against": ["stem borer, leaf folder, thrips, diamondback moth"], "application_method": ["foliar spray"], "form": "WG", "solubility": "water dispersible", "manufacturer": "Bayer", "storage_instructions": "Store in cool dry place.", "additional": {}}'::jsonb FROM input_item_categories WHERE code = 'PESTICIDE' UNION ALL 
SELECT id, 'KARATE', true, 1, true, '{"trade_name": "Karate", "brand": "Syngenta", "category": "insecticide (pyrethroid)", "active_ingredients": ["Lambda-cyhalothrin 5% EC"], "mode_of_action": ["contact and ingestion (sodium channel modulator)"], "effective_against": ["chewing and sucking pests"], "application_method": ["foliar spray"], "form": "EC", "solubility": "emulsifiable", "manufacturer": "Syngenta", "storage_instructions": "Store in cool dry place.", "additional": {}}'::jsonb FROM input_item_categories WHERE code = 'PESTICIDE' UNION ALL 
SELECT id, 'MAGISTER', true, 1, true, '{"trade_name": "Magister", "brand": "Corteva", "category": "miticide", "active_ingredients": ["Fenazaquin 10% EC"], "mode_of_action": ["contact/ingestion"], "effective_against": ["mite pests"], "application_method": ["foliar spray"], "form": "EC", "solubility": "emulsifiable", "manufacturer": "Corteva", "storage_instructions": "Store cool dry.", "additional": {}}'::jsonb FROM input_item_categories WHERE code = 'PESTICIDE' UNION ALL 
SELECT id, 'PEGASUS', true, 1, true, '{"trade_name": "Pegasus", "brand": "Syngenta", "category": "insecticide/miticide", "active_ingredients": ["Diafenthiuron 50% WP"], "mode_of_action": ["contact/prolonged residual"], "effective_against": ["mites, some chewing insects"], "application_method": ["foliar spray"], "form": "WP", "solubility": "suspendable", "manufacturer": "Syngenta", "storage_instructions": "Store dry.", "additional": {}}'::jsonb FROM input_item_categories WHERE code = 'PESTICIDE' UNION ALL 
SELECT id, 'PROCLAIM', true, 1, true, '{"trade_name": "Proclaim", "brand": "Syngenta", "category": "insecticide (avermectin group)", "active_ingredients": ["Emamectin benzoate 5% SG"], "mode_of_action": ["ingestion, translaminar"], "effective_against": ["lepidopteran larvae"], "application_method": ["foliar spray"], "form": "SG", "solubility": "water dispersible", "manufacturer": "Syngenta", "storage_instructions": "Store cool dry.", "additional": {}}'::jsonb FROM input_item_categories WHERE code = 'PESTICIDE' UNION ALL 
SELECT id, 'REGENT', true, 1, true, '{"trade_name": "Regent", "brand": "Bayer", "category": "insecticide (phenylpyrazole)", "active_ingredients": ["Fipronil 0.6% GR"], "mode_of_action": ["contact & stomach action"], "effective_against": ["stem borer, leaf folder"], "application_method": ["soil application"], "form": "GR", "solubility": "granular", "manufacturer": "Bayer", "storage_instructions": "Store cool dry.", "additional": {}}'::jsonb FROM input_item_categories WHERE code = 'PESTICIDE' UNION ALL 
SELECT id, 'ROGOR', true, 1, true, '{"trade_name": "Rogor", "brand": "FMC", "category": "insecticide (organophosphate)", "active_ingredients": ["Dimethoate 30% EC"], "mode_of_action": ["systemic/contact"], "effective_against": ["aphids, thrips, mites"], "application_method": ["foliar spray"], "form": "EC", "solubility": "emulsifiable", "manufacturer": "FMC", "storage_instructions": "Store cool dry.", "additional": {}}'::jsonb FROM input_item_categories WHERE code = 'PESTICIDE' UNION ALL 
SELECT id, 'ULALA', true, 1, true, '{"trade_name": "Ulala", "brand": "UPL", "category": "insecticide (sucking pest)", "active_ingredients": ["Flonicamid 50% WG"], "mode_of_action": ["feeding blocker"], "effective_against": ["aphids, jassids, whiteflies"], "application_method": ["foliar spray"], "form": "WG", "solubility": "water dispersible", "manufacturer": "UPL", "storage_instructions": "Store cool dry.", "additional": {}}'::jsonb FROM input_item_categories WHERE code = 'PESTICIDE' UNION ALL 
SELECT id, 'GRACIA', true, 1, true, '{"trade_name": "Gracia", "brand": "Godrej Agrovet", "category": "insecticide", "active_ingredients": ["Fluxametamide 10% EC"], "mode_of_action": ["ingestion/contact"], "effective_against": ["caterpillars"], "application_method": ["foliar spray"], "form": "EC", "solubility": "emulsifiable", "manufacturer": "Godrej Agrovet", "storage_instructions": "Store cool dry.", "additional": {}}'::jsonb FROM input_item_categories WHERE code = 'PESTICIDE' UNION ALL 
SELECT id, 'EXPONUS', true, 1, true, '{"trade_name": "Exponus", "brand": "BASF", "category": "insecticide", "active_ingredients": ["Broflanilide 300 g/L SC"], "mode_of_action": ["GABA modulator"], "effective_against": ["borers, chewing pests"], "application_method": ["foliar spray"], "form": "SC", "solubility": "suspension", "manufacturer": "BASF", "storage_instructions": "Store cool dry.", "additional": {}}'::jsonb FROM input_item_categories WHERE code = 'PESTICIDE' UNION ALL 
SELECT id, 'SIMODIS', true, 1, true, '{"trade_name": "Simodis", "brand": "Syngenta", "category": "insecticide", "active_ingredients": ["Isocycloseram 10% DC"], "mode_of_action": ["GABA modulator"], "effective_against": ["sucking & chewing pests"], "application_method": ["foliar spray"], "form": "DC", "solubility": "dispersible", "manufacturer": "Syngenta", "storage_instructions": "Store cool dry.", "additional": {}}'::jsonb FROM input_item_categories WHERE code = 'PESTICIDE' UNION ALL 
SELECT id, 'MOVENTO_ENERGY', true, 1, true, '{"trade_name": "Movento Energy", "brand": "Bayer", "category": "insecticide (systemic)", "active_ingredients": ["Spirotetramat 150 OD"], "mode_of_action": ["two-way systemic"], "effective_against": ["sucking pests"], "application_method": ["foliar spray"], "form": "OD", "solubility": "oil dispersion", "manufacturer": "Bayer", "storage_instructions": "Store cool dry.", "additional": {}}'::jsonb FROM input_item_categories WHERE code = 'PESTICIDE' UNION ALL 
SELECT id, 'AMISTAR', true, 1, true, '{"trade_name": "Amistar", "brand": "Syngenta", "category": "fungicide", "active_ingredients": ["Azoxystrobin 23% SC"], "mode_of_action": ["QoI"], "effective_against": ["rust, blight, leaf spot"], "application_method": ["foliar spray"], "form": "SC", "solubility": "suspension", "manufacturer": "Syngenta", "storage_instructions": "Store cool dry.", "additional": {}}'::jsonb FROM input_item_categories WHERE code = 'PESTICIDE' UNION ALL 
SELECT id, 'AMISTAR_TOP', true, 1, true, '{"trade_name": "Amistar Top", "brand": "Syngenta", "category": "fungicide (mix)", "active_ingredients": ["Azoxystrobin 18.2% + Difenoconazole 11.4% SC"], "mode_of_action": ["QoI + DMI"], "effective_against": ["blights, leaf spots"], "application_method": ["foliar spray"], "form": "SC", "solubility": "suspension", "manufacturer": "Syngenta", "storage_instructions": "Store cool dry.", "additional": {}}'::jsonb FROM input_item_categories WHERE code = 'PESTICIDE' UNION ALL 
SELECT id, 'BAVISTIN', true, 1, true, '{"trade_name": "Bavistin", "brand": "Multiple", "category": "fungicide", "active_ingredients": ["Carbendazim 50% WP"], "mode_of_action": ["systemic"], "effective_against": ["wilt, rot diseases"], "application_method": ["seed treatment", "soil drench", "foliar spray"], "form": "WP", "solubility": "suspendable", "manufacturer": "Multiple", "storage_instructions": "Store cool dry.", "additional": {}}'::jsonb FROM input_item_categories WHERE code = 'PESTICIDE' UNION ALL 
SELECT id, 'EQUATION_PRO', true, 1, true, '{"trade_name": "Equation Pro", "brand": "Corteva", "category": "fungicide", "active_ingredients": ["(varies; Corteva SKU)"], "mode_of_action": ["protectant + curative"], "effective_against": ["oomycetes"], "application_method": ["foliar spray"], "form": "SC/WG", "solubility": "varies", "manufacturer": "Corteva", "storage_instructions": "Store cool dry.", "additional": {}}'::jsonb FROM input_item_categories WHERE code = 'PESTICIDE' UNION ALL 
SELECT id, 'KOCIDE', true, 1, true, '{"trade_name": "Kocide", "brand": "Corteva", "category": "fungicide/bactericide", "active_ingredients": ["Copper hydroxide"], "mode_of_action": ["contact"], "effective_against": ["leaf spots, blights"], "application_method": ["foliar spray"], "form": "DF/WG", "solubility": "suspendable", "manufacturer": "Corteva", "storage_instructions": "Store dry.", "additional": {}}'::jsonb FROM input_item_categories WHERE code = 'PESTICIDE' UNION ALL 
SELECT id, 'NATIVO', true, 1, true, '{"trade_name": "Nativo", "brand": "Bayer", "category": "fungicide (mix)", "active_ingredients": ["Trifloxystrobin 25% + Tebuconazole 50% WG"], "mode_of_action": ["QoI + DMI"], "effective_against": ["broad fungal diseases"], "application_method": ["foliar spray"], "form": "WG", "solubility": "water dispersible", "manufacturer": "Bayer", "storage_instructions": "Store cool dry.", "additional": {}}'::jsonb FROM input_item_categories WHERE code = 'PESTICIDE' UNION ALL 
SELECT id, 'PROFILER', true, 1, true, '{"trade_name": "Profiler", "brand": "Bayer", "category": "fungicide", "active_ingredients": ["Fluopicolide 4.44% + Fosetyl-Al 66.67% WG"], "mode_of_action": ["systemic + contact"], "effective_against": ["downy mildew"], "application_method": ["foliar spray"], "form": "WG", "solubility": "water dispersible", "manufacturer": "Bayer", "storage_instructions": "Store cool dry.", "additional": {}}'::jsonb FROM input_item_categories WHERE code = 'PESTICIDE' UNION ALL 
SELECT id, 'RIDOMIL_GOLD', true, 1, true, '{"trade_name": "Ridomil Gold", "brand": "Syngenta", "category": "fungicide", "active_ingredients": ["Metalaxyl-M 4% + Mancozeb 64% WP"], "mode_of_action": ["systemic + protectant"], "effective_against": ["late blight, downy mildew"], "application_method": ["foliar spray", "soil drench"], "form": "WP", "solubility": "suspendable", "manufacturer": "Syngenta", "storage_instructions": "Store dry.", "additional": {}}'::jsonb FROM input_item_categories WHERE code = 'PESTICIDE' UNION ALL 
SELECT id, 'GALILEO_SENSA', true, 1, true, '{"trade_name": "Galileo Sensa", "brand": "Corteva", "category": "fungicide", "active_ingredients": ["(Corteva SKU)"], "mode_of_action": ["preventive + curative"], "effective_against": ["blast, mildew"], "application_method": ["foliar spray"], "form": "SC/WG", "solubility": "varies", "manufacturer": "Corteva", "storage_instructions": "Store dry.", "additional": {}}'::jsonb FROM input_item_categories WHERE code = 'PESTICIDE' UNION ALL 
SELECT id, 'SAFINA', true, 1, true, '{"trade_name": "Safina", "brand": "Multiple", "category": "unknown", "active_ingredients": [null], "mode_of_action": [null], "effective_against": [null], "application_method": [null], "form": null, "solubility": null, "manufacturer": null, "storage_instructions": null, "additional": {"notes": "Ambiguous SKU name"}}'::jsonb FROM input_item_categories WHERE code = 'PESTICIDE' UNION ALL 
SELECT id, 'SUMIPREMPT', true, 1, true, '{"trade_name": "Sumiprempt", "brand": "Sumitomo", "category": "insecticide (mix)", "active_ingredients": ["Pyriproxyfen 5% + Fenpropathrin 15% EC"], "mode_of_action": ["growth regulator + sodium channel modulator"], "effective_against": ["whiteflies", "borers"], "application_method": ["foliar spray"], "form": "EC", "solubility": "emulsifiable", "manufacturer": "Sumitomo", "storage_instructions": "Store cool dry.", "additional": {}}'::jsonb FROM input_item_categories WHERE code = 'PESTICIDE' UNION ALL 
SELECT id, 'CUSTODIA', true, 1, true, '{"trade_name": "Custodia", "brand": "Adama", "category": "fungicide (mix)", "active_ingredients": ["Azoxystrobin 11% + Tebuconazole 18.3% SC"], "mode_of_action": ["QoI + DMI"], "effective_against": ["broad fungal diseases"], "application_method": ["foliar spray"], "form": "SC", "solubility": "suspension", "manufacturer": "Adama", "storage_instructions": "Store cool dry.", "additional": {}}'::jsonb FROM input_item_categories WHERE code = 'PESTICIDE' UNION ALL 
SELECT id, 'SALIBRO', true, 1, true, '{"trade_name": "Salibro", "brand": "Corteva", "category": "nematicide", "active_ingredients": ["(Corteva SKU)"], "mode_of_action": ["nematicidal"], "effective_against": ["nematodes"], "application_method": ["soil application"], "form": "liquid", "solubility": "varies", "manufacturer": "Corteva", "storage_instructions": "Store cool dry.", "additional": {}}'::jsonb FROM input_item_categories WHERE code = 'PESTICIDE' UNION ALL 
SELECT id, 'TAGMYCIN', true, 1, true, '{"trade_name": "Tagmycin", "brand": "Multiple", "category": "bactericide (antibiotic)", "active_ingredients": ["Streptomycin + Tetracycline"], "mode_of_action": ["bactericidal"], "effective_against": ["bacterial leaf spots"], "application_method": ["foliar spray"], "form": "powder", "solubility": "water soluble", "manufacturer": "Multiple", "storage_instructions": "Store away from sunlight.", "additional": {"regulatory_note": "Use regulated"}}'::jsonb FROM input_item_categories WHERE code = 'PESTICIDE'
ON CONFLICT (code, is_system_defined) WHERE is_system_defined = TRUE DO NOTHING;


INSERT INTO input_item_translations (input_item_id, language_code, name) VALUES 
((SELECT id from input_items where code='ACTARA') , 'en', 'Actara'), 
((SELECT id from input_items where code='ADMIRE') , 'en', 'Admire'), 
((SELECT id from input_items where code='CONFIDOR') , 'en', 'Confidor'), 
((SELECT id from input_items where code='CORAGEN') , 'en', 'Coragen'), 
((SELECT id from input_items where code='JUMP') , 'en', 'Jump'), 
((SELECT id from input_items where code='KARATE') , 'en', 'Karate'), 
((SELECT id from input_items where code='MAGISTER') , 'en', 'Magister'), 
((SELECT id from input_items where code='PEGASUS') , 'en', 'Pegasus'), 
((SELECT id from input_items where code='PROCLAIM') , 'en', 'Proclaim'), 
((SELECT id from input_items where code='REGENT') , 'en', 'Regent'), 
((SELECT id from input_items where code='ROGOR') , 'en', 'Rogor'), 
((SELECT id from input_items where code='ULALA') , 'en', 'Ulala'), 
((SELECT id from input_items where code='GRACIA') , 'en', 'Gracia'), 
((SELECT id from input_items where code='EXPONUS') , 'en', 'Exponus'), 
((SELECT id from input_items where code='SIMODIS') , 'en', 'Simodis'), 
((SELECT id from input_items where code='MOVENTO_ENERGY') , 'en', 'Movento Energy'), 
((SELECT id from input_items where code='AMISTAR') , 'en', 'Amistar'), 
((SELECT id from input_items where code='AMISTAR_TOP') , 'en', 'Amistar Top'), 
((SELECT id from input_items where code='BAVISTIN') , 'en', 'Bavistin'), 
((SELECT id from input_items where code='EQUATION_PRO') , 'en', 'Equation Pro'), 
((SELECT id from input_items where code='KOCIDE') , 'en', 'Kocide'), 
((SELECT id from input_items where code='NATIVO') , 'en', 'Nativo'), 
((SELECT id from input_items where code='PROFILER') , 'en', 'Profiler'), 
((SELECT id from input_items where code='RIDOMIL_GOLD') , 'en', 'Ridomil Gold'), 
((SELECT id from input_items where code='GALILEO_SENSA') , 'en', 'Galileo Sensa'), 
((SELECT id from input_items where code='SAFINA') , 'en', 'Safina'), 
((SELECT id from input_items where code='SUMIPREMPT') , 'en', 'Sumiprempt'), 
((SELECT id from input_items where code='CUSTODIA') , 'en', 'Custodia'), 
((SELECT id from input_items where code='SALIBRO') , 'en', 'Salibro'), 
((SELECT id from input_items where code='TAGMYCIN') , 'en', 'Tagmycin'), 
((SELECT id from input_items where code='ACTARA') , 'ta', 'ஆக்டரா'), 
((SELECT id from input_items where code='ADMIRE') , 'ta', 'அட்மைர்'), 
((SELECT id from input_items where code='CONFIDOR') , 'ta', 'கான்ஃபிடர்'), 
((SELECT id from input_items where code='CORAGEN') , 'ta', 'கோரஜென்'), 
((SELECT id from input_items where code='JUMP') , 'ta', 'ஜம்ப்'), 
((SELECT id from input_items where code='KARATE') , 'ta', 'கராத்தே'), 
((SELECT id from input_items where code='MAGISTER') , 'ta', 'மாஜிஸ்டர்'), 
((SELECT id from input_items where code='PEGASUS') , 'ta', 'பெகாசஸ்'), 
((SELECT id from input_items where code='PROCLAIM') , 'ta', 'பிராக்ளேம்'), 
((SELECT id from input_items where code='REGENT') , 'ta', 'ரீஜண்ட்'), 
((SELECT id from input_items where code='ROGOR') , 'ta', 'ரோகோர்'), 
((SELECT id from input_items where code='ULALA') , 'ta', 'உலால'), 
((SELECT id from input_items where code='GRACIA') , 'ta', 'கிரேசியா'), 
((SELECT id from input_items where code='EXPONUS') , 'ta', 'எக்ஸ்போனஸ்'), 
((SELECT id from input_items where code='SIMODIS') , 'ta', 'சிமோடிஸ்'), 
((SELECT id from input_items where code='MOVENTO_ENERGY') , 'ta', 'மூவெண்டோ எனர்ஜி'), 
((SELECT id from input_items where code='AMISTAR') , 'ta', 'அமிஸ்டர்'), 
((SELECT id from input_items where code='AMISTAR_TOP') , 'ta', 'அமிஸ்டர் டாப்'), 
((SELECT id from input_items where code='BAVISTIN') , 'ta', 'பாவிஸ்டின்'), 
((SELECT id from input_items where code='EQUATION_PRO') , 'ta', 'ஈக்குவேஷன் ப்ரோ'), 
((SELECT id from input_items where code='KOCIDE') , 'ta', 'கோசைட்'), 
((SELECT id from input_items where code='NATIVO') , 'ta', 'நேட்டிவோ'), 
((SELECT id from input_items where code='PROFILER') , 'ta', 'பிரோஃபைலர்'), 
((SELECT id from input_items where code='RIDOMIL_GOLD') , 'ta', 'ரிடோமில் கோல்டு'), 
((SELECT id from input_items where code='GALILEO_SENSA') , 'ta', 'கலிலியோ சென்சா'), 
((SELECT id from input_items where code='SAFINA') , 'ta', 'சஃபினா'), 
((SELECT id from input_items where code='SUMIPREMPT') , 'ta', 'சுமிப்ரெம்ப்ட்'), 
((SELECT id from input_items where code='CUSTODIA') , 'ta', 'கஸ்டோடியா'), 
((SELECT id from input_items where code='SALIBRO') , 'ta', 'சாலிப்ரோ'), 
((SELECT id from input_items where code='TAGMYCIN') , 'ta', 'டாக்மைசின்'), 
((SELECT id from input_items where code='ACTARA') , 'ml', 'ആക്താര'), 
((SELECT id from input_items where code='ADMIRE') , 'ml', 'അഡ്‌മയർ'), 
((SELECT id from input_items where code='CONFIDOR') , 'ml', 'കോൺഫിഡോർ'), 
((SELECT id from input_items where code='CORAGEN') , 'ml', 'കോരജൻ'), 
((SELECT id from input_items where code='JUMP') , 'ml', 'ജമ്പ്'), 
((SELECT id from input_items where code='KARATE') , 'ml', 'കരാട്ടെ'), 
((SELECT id from input_items where code='MAGISTER') , 'ml', 'മജിസ്റ്റർ'), 
((SELECT id from input_items where code='PEGASUS') , 'ml', 'പെഗാസസ്'), 
((SELECT id from input_items where code='PROCLAIM') , 'ml', 'പ്രോക്ലെയിം'), 
((SELECT id from input_items where code='REGENT') , 'ml', 'റീജൻ്റ്'), 
((SELECT id from input_items where code='ROGOR') , 'ml', 'റോഗോർ'), 
((SELECT id from input_items where code='ULALA') , 'ml', 'ഉലാല'), 
((SELECT id from input_items where code='GRACIA') , 'ml', 'ഗ്രേഷ്യ'), 
((SELECT id from input_items where code='EXPONUS') , 'ml', 'എക്സ്പോണസ്'), 
((SELECT id from input_items where code='SIMODIS') , 'ml', 'സിമോഡിസ്'), 
((SELECT id from input_items where code='MOVENTO_ENERGY') , 'ml', 'Movento എനർജി'), 
((SELECT id from input_items where code='AMISTAR') , 'ml', 'അമിസ്റ്റാർ'), 
((SELECT id from input_items where code='AMISTAR_TOP') , 'ml', 'അമിസ്റ്റാർ ടോപ്പ്'), 
((SELECT id from input_items where code='BAVISTIN') , 'ml', 'ബാവിസ്റ്റിൻ'), 
((SELECT id from input_items where code='EQUATION_PRO') , 'ml', ' ഇക്വേഷൻ പ്രോ'), 
((SELECT id from input_items where code='KOCIDE') , 'ml', 'കോസിഡെ'), 
((SELECT id from input_items where code='NATIVO') , 'ml', 'നേറ്റിവോ'), 
((SELECT id from input_items where code='PROFILER') , 'ml', 'പ്രൊഫൈലർ'), 
((SELECT id from input_items where code='RIDOMIL_GOLD') , 'ml', 'റിഡോമിൽ ഗോൾഡ്'), 
((SELECT id from input_items where code='GALILEO_SENSA') , 'ml', 'ഗലീലിയോ സെൻസ'), 
((SELECT id from input_items where code='SAFINA') , 'ml', 'സഫീന'), 
((SELECT id from input_items where code='SUMIPREMPT') , 'ml', 'സുമിപ്രേംപ്റ്റ്'), 
((SELECT id from input_items where code='CUSTODIA') , 'ml', 'കസ്റ്റോഡിയ'), 
((SELECT id from input_items where code='SALIBRO') , 'ml', 'സാലിബ്രോ'), 
((SELECT id from input_items where code='TAGMYCIN') , 'ml', 'ടാഗ്മൈസിൻ')
ON CONFLICT (input_item_id, language_code) DO NOTHING;